### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ShevKG** [lehoanganh298/json-lines-viewer#1]
Can you please add a support for hot keys? It would be great to switch between JSON lines using a keyboard :)

**Comment by lehoanganh298** [comment]
It can be done by mapping the available extension commands `JSONL Next Line` or `JSONL Previous Line` to specific VSCode Keyboard Shortcut.
1. Open VSCode Keyboard Shortcut (Ctrl+K -> Ctrl+S)
2. Search JSONL
3. Set your desired hot keys to corresponding command commands.

An example in the image below
![image](https://github.com/lehoanganh298/json-lines-viewer/assets/26211584/bbeb311e-0d3a-46c7-979a-06258c25b65e)

Let me know if this doesn't work for you.
