### ISSUE TITLE
There seems to be cache?

### ISSUE THREAD

**Issue by Ignoramus0817** [lehoanganh298/json-lines-viewer#2]
Once I view a file use the extension, modifications of the original file will not be shown in the previews, even I close and reopen the preview and the original file. 
Only reloading the window or renaming the file can make me preview the modified content.
Is it expected or a bug? Is there a way to disable such cache?

**Comment by lehoanganh298** [comment]
I also notice that bug and would plan to fix that.
There's a quick work around in the meantime. You do not need to reload the window, just move to a different line (using `JSONL Next Line` or `JSONL Previous Line` button) will refresh the cache content (e.g you previewing line x of the file with outdated content, go to next line using `JSONL Next Line`, then go to previous line using `JSONL Previous Line` will see the content of line x updated).
Let me know if that work for you.

**Comment by Ignoramus0817** [comment]
Switching to another line works for me. Thanks for your reply!
